version: "3"
services:
  app:
    image: bjornlindholm/laravel:7.4
    networks:
      - appnet
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    working_dir: /var/www/html
  cache:
    image: redis:6
    networks:
      - appnet
    volumes:
      - cachedata:/data
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    networks:
      - appnet
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
  node:
    image: bjornlindholm/node:12
    networks:
      - appnet
    volumes:
      - ./:/opt
    working_dir: /opt
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local
